[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Tim Steff <tsteff@gmail.com>"]
edition = "2018"
description = "Learning rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
